name: Build Integrity
on: [push]
jobs:
  build-everything:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2.2.1
      - run:  zig build -Deverything=true

