name: Internals exposure Verification and Build Integrity
run-name: test builds based on changes pushed by ${{ github.actor }}
on: [push]
jobs:
  check-exposed-internal-typedefs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: |
          grep -zq '#include "_escdef.h"' ./include/*.h \
            && echo -e "\ntypedefs in ./include/_escdef.h are for INTERNAL. USE. ONLY.\n" \
            && grep -i -B256 '#include "_escdef.h"' ./include/*.h \
            || echo "No internal typedefs included in public library headers, everything is fine."
  build-everything:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: .
          args: |
            build -Deverything=true --summary all
          working-directory: example
        env:
          ZIG_VERSION: 0.15.2

