name: Internals exposure Verification and Build Integrity
run-name: test builds based on changes pushed by ${{ github.actor }}
on: [push]
jobs:
  check-exposed-internal-typedefs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: |
          grep -zq '#include "_escdef.h"' ./include/*.h \
            && echo -e "\ntypedefs in ./include/_escdef.h are for INTERNAL. USE. ONLY.\n" \
            && grep -i -B256 '#include "_escdef.h"' ./include/*.h \
            || echo "No internal typedefs included in public library headers, everything is fine."
  build-everything:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: zig
          version: 1.0
        run: ~/zig-bin/zig build -Deverything=true

