name: Build Tests and Clang Format Checker
run-name: Checking format and testing builds based on changes pushed by ${{ github.actor }}.
on: [push]
jobs:
  format-checking-make-all-targets:
    runs-on: ubuntu-latest
    steps:
      - name: source code format checking based on .clang-format and makes all target

      - uses: actions/checkout@latest

      - uses: RafikFarhad/clang-format-github-action@latest
        with:
          sources: "src/*.h,src/*.c,test/*.c"
          style: file

      - run: make everything -j

