name: Format/Internals exposure Verification and Build Integrity
run-name: Check format and test builds based on changes pushed by ${{ github.actor }}
on: [push]
jobs:
  check-exposed-internal-typedefs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: |
        grep -zq '#include "_escdef.h"' ./include/* \
            && echo -e "\ntypedefs in ./include/_escdef.h are for INTERNAL. USE. ONLY.\n" \
            && grep -i -B256 '#include "_escdef.h"' ./include/* \
        || echo "No internal typedefs included in public library headers."

  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: RafikFarhad/clang-format-github-action@v5
        with:
          sources: "src/*.c,include/*.h,test/*.c"
          style: file
  make-every-target:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: clang
          version: 1.0
      - run: make everything CC=clang -j

