name: Clang Format Checker
run-name: Formatting files ${{ github.actor }} pushed recently
on: [push]
jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: RafikFarhad/clang-format-github-action@v5
        with:
          sources: "src/**/*.h,src/**/*.c,test/**/*.c"
          style: file

