name: Build Tests and Clang Format Checker
run-name: Checking format and testing builds based on changes pushed by ${{ github.actor }}.
on: [push]
jobs:
  format-checking-make-all-targets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: RafikFarhad/clang-format-github-action@v5
        with:
          sources: "src/*.h,include/*.c,test/*.c"
          style: file

      - run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test

      - run: make everything -j

